#!/bin/bash

# Script to add new Swift files to Xcode project
# Run this from the project root directory

echo "================================"
echo "Millionaires Culture - File Setup"
echo "================================"
echo ""
echo "The following files have been created for your game:"
echo ""
echo "Models:"
echo "  - Models/Question.swift"
echo ""
echo "ViewModels:"
echo "  - ViewModels/GameViewModel.swift"
echo ""
echo "Views:"
echo "  - Views/MenuView.swift"
echo "  - Views/GameView.swift"
echo "  - Views/PrizeLadderView.swift"
echo ""
echo "================================"
echo "IMPORTANT: Manual Steps Required"
echo "================================"
echo ""
echo "These files need to be added to your Xcode project:"
echo ""
echo "1. Open 'Millionaires Culture.xcodeproj' in Xcode"
echo ""
echo "2. In Xcode, right-click on 'Millionaires Culture' folder"
echo "   (the blue folder icon in the project navigator)"
echo ""
echo "3. Select 'Add Files to \"Millionaires Culture\"...'"
echo ""
echo "4. Navigate to and select these folders:"
echo "   - Models (contains Question.swift)"
echo "   - ViewModels (contains GameViewModel.swift)"
echo "   - Views (contains MenuView.swift, GameView.swift, PrizeLadderView.swift)"
echo ""
echo "5. Make sure to check:"
echo "   ☑ 'Copy items if needed' (should be UNCHECKED - files are already in place)"
echo "   ☑ 'Create groups' (should be SELECTED)"
echo "   ☑ 'Add to targets: Millionaires Culture' (should be CHECKED)"
echo ""
echo "6. Click 'Add'"
echo ""
echo "7. Build and run the project (Cmd+R)"
echo ""
echo "================================"
echo "Alternative: Use Xcode's File > Add Files menu"
echo "================================"
echo ""

# List the files with their full paths
echo "File locations:"
echo ""
find "Millionaires Culture" -name "*.swift" -type f | grep -E "(Models|ViewModels|Views)" | sort

echo ""
echo "================================"
echo "After adding files, your project structure should look like:"
echo "================================"
echo ""
echo "Millionaires Culture/"
echo "├── Models/"
echo "│   └── Question.swift"
echo "├── ViewModels/"
echo "│   └── GameViewModel.swift"
echo "├── Views/"
echo "│   ├── GameView.swift"
echo "│   ├── MenuView.swift"
echo "│   └── PrizeLadderView.swift"
echo "├── ContentView.swift"
echo "├── Millionaires_CultureApp.swift"
echo "└── Assets.xcassets/"
echo ""
